CREATE TABLE file_object_gc (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    object_name VARCHAR(1024) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
